import React, { useState } from "react";
import { MetabolomicsData, ActiveMetaboliteItem } from "../types";
import { evaluateMetabolomics } from "../utils/forensicCalculations";
import { formatIndicatorTimestamp } from "../utils/validation";
import {
  TestTube2,
  AlertCircle,
  Info,
  CheckCircle2,
  FlaskConical,
  ChevronDown,
  ChevronUp,
  HelpCircle,
  Plus,
  Trash2,
  Activity,
  Sparkles,
  Clock,
  ShieldAlert,
  ArrowRight,
  Gauge,
  Droplets,
  Zap,
} from "lucide-react";

interface Props {
  data: MetabolomicsData;
  onChange: (updated: MetabolomicsData) => void;
  isOpen?: boolean;
  onToggleOpen?: () => void;
}

// Predefined catalog of forensic metabolites available from dropdown
const METABOLITE_CATALOG = [
  {
    key: "vitreous_potassium",
    name: "Vitreous Potassium ([K⁺])",
    unit: "mmol/L",
    defaultVal: 6.5,
    min: 3.5,
    max: 20.0,
    step: 0.1,
    referenceRange: "3.5 – 5.0 mmol/L (Antemortem baseline)",
    description: "Post-mortem retinal autolysis releasing intracellular potassium in linear kinetics (0–72h).",
    calculatePmi: (val: number) => {
      const pmiMadea = Math.max(0, 5.26 * (val - 4.0));
      const pmiSturner = Math.max(0, 7.14 * val - 39.1);
      return val <= 4.0 ? 1.5 : (pmiMadea + pmiSturner) / 2;
    },
  },
  {
    key: "vitreous_hypoxanthine",
    name: "Vitreous Hypoxanthine (Hx)",
    unit: "µmol/L",
    defaultVal: 65,
    min: 10,
    max: 250,
    step: 1,
    referenceRange: "0 – 25 µmol/L (Antemortem physiologic)",
    description: "Purine nucleotide catabolite generated by ATP degradation during tissue hypoxia (0–48h).",
    calculatePmi: (val: number) => {
      // Rognum & Saugstad linear regression: PMI ≈ (Hx - 20) / 3.8
      return Math.max(1, Math.min(72, (val - 20) / 3.8));
    },
  },
  {
    key: "vitreous_lactate",
    name: "Vitreous L-Lactate",
    unit: "mmol/L",
    defaultVal: 16.5,
    min: 5,
    max: 40,
    step: 0.5,
    referenceRange: "5 – 11 mmol/L (Normal antemortem)",
    description: "Anaerobic post-mortem glycolysis marker, peaking within first 24 hours.",
    calculatePmi: (val: number) => {
      // Linear slope for early post-mortem anaerobic glycolysis
      return Math.max(1, Math.min(36, (val - 7.5) * 1.6));
    },
  },
  {
    key: "urea_nitrogen",
    name: "Vitreous Urea Nitrogen (VUN)",
    unit: "mg/dL",
    defaultVal: 22,
    min: 8,
    max: 120,
    step: 1,
    referenceRange: "10 – 25 mg/dL (Antemortem baseline)",
    description: "Post-mortem stable renal validator. VUN > 35–40 mg/dL confirms antemortem azotemia/uremia, requiring baseline [K⁺] offset correction to avoid gross PMI overestimation.",
    calculatePmi: (_val: number) => 0, // Diagnostic validator & correction coefficient
  },
  {
    key: "vitreous_sodium",
    name: "Vitreous Sodium ([Na⁺])",
    unit: "mmol/L",
    defaultVal: 138,
    min: 100,
    max: 180,
    step: 1,
    referenceRange: "135 – 150 mmol/L (Normal equilibrium)",
    description: "Demonstrates slow linear decline (~0.5 mmol/L/h) from 142 baseline. Identifies severe dehydration (>152) or hemodilution (<125) that skews [K⁺].",
    calculatePmi: (val: number) => {
      // Linear post-mortem decline from ~142 baseline at ~0.5 mmol/L per hour (Coe / Madea)
      return val <= 142 ? Math.max(1, Math.min(72, Number(((142 - val) / 0.5).toFixed(1)))) : 1;
    },
  },
  {
    key: "vitreous_glucose",
    name: "Vitreous Glucose",
    unit: "mg/dL",
    defaultVal: 15,
    min: 0,
    max: 300,
    step: 1,
    referenceRange: "0 – 80 mg/dL (Drops rapidly post-mortem)",
    description: "Rapidly metabolized by retinal cells post-mortem; drops near 0 within 6–12h. Useful for diabetic ketoacidosis.",
    calculatePmi: (val: number) => {
      return val > 100 ? 1 : Math.max(1, 14 - (val / 10));
    },
  },
  {
    key: "vitreous_inosine",
    name: "Vitreous Inosine",
    unit: "µmol/L",
    defaultVal: 35,
    min: 5,
    max: 120,
    step: 1,
    referenceRange: "2 – 10 µmol/L (Antemortem baseline)",
    description: "Precursor to hypoxanthine in adenine nucleotide breakdown cascade (early 0–24h marker).",
    calculatePmi: (val: number) => {
      return Math.max(1, Math.min(36, (val - 5) / 2.8));
    },
  },
  {
    key: "csf_amino_acids",
    name: "CSF Amino Acids (GABA / Glycine)",
    unit: "µmol/L",
    defaultVal: 8.5,
    min: 1,
    max: 30,
    step: 0.5,
    referenceRange: "0.5 – 3.0 µmol/L (Physiological)",
    description: "Central nervous system ischemia marker demonstrating steady autolytic rise across 0–48 hours.",
    calculatePmi: (val: number) => {
      return Math.max(1, Math.min(48, (val - 1.5) * 2.2));
    },
  },
];

export const MetabolomicsInput: React.FC<Props> = ({
  data,
  onChange,
  isOpen,
  onToggleOpen,
}) => {
  const [internalCollapsed, setInternalCollapsed] = useState(false);
  const [selectedCatalogKey, setSelectedCatalogKey] = useState<string>("vitreous_hypoxanthine");
  const [showExtraInfo, setShowExtraInfo] = useState(false);

  // Controlled collapse state (from parent or internal)
  const isCollapsed = isOpen !== undefined ? !isOpen : internalCollapsed;
  const toggleCollapse = () => {
    if (onToggleOpen) onToggleOpen();
    else setInternalCollapsed(!internalCollapsed);
  };

  const result = evaluateMetabolomics(data);
  const activeMetabolites = data.selectedMetabolites || [];

  // Add metabolite from dropdown
  const handleAddMetabolite = () => {
    const itemMeta = METABOLITE_CATALOG.find((m) => m.key === selectedCatalogKey);
    if (!itemMeta) return;

    // Prevent duplicate entries
    const existing = activeMetabolites.find((m) => m.metaboliteKey === itemMeta.key);
    if (existing) return;

    const calcPmi = Number(itemMeta.calculatePmi(itemMeta.defaultVal).toFixed(1));
    const newItem: ActiveMetaboliteItem = {
      id: `metab-${Date.now()}-${Math.random().toString(36).substr(2, 4)}`,
      metaboliteKey: itemMeta.key,
      name: itemMeta.name,
      measuredValue: itemMeta.defaultVal,
      unit: itemMeta.unit,
      referenceRange: itemMeta.referenceRange,
      pmiContributionHours: calcPmi,
      confidence: calcPmi > 0 ? 85 : 90,
      notes: itemMeta.description,
    };

    const updatedList = [...activeMetabolites, newItem];
    onChange({
      ...data,
      selectedMetabolites: updatedList,
    });
  };

  // Remove metabolite
  const handleRemoveMetabolite = (id: string) => {
    const updatedList = activeMetabolites.filter((m) => m.id !== id);
    onChange({
      ...data,
      selectedMetabolites: updatedList,
    });
  };

  // Update metabolite value
  const handleUpdateMetaboliteValue = (id: string, newVal: number) => {
    const updatedList = activeMetabolites.map((m) => {
      if (m.id !== id) return m;
      const catalogItem = METABOLITE_CATALOG.find((cat) => cat.key === m.metaboliteKey);
      const newPmi = catalogItem ? Number(catalogItem.calculatePmi(newVal).toFixed(1)) : m.pmiContributionHours;
      return {
        ...m,
        measuredValue: newVal,
        pmiContributionHours: newPmi,
      };
    });

    onChange({
      ...data,
      selectedMetabolites: updatedList,
    });
  };

  const k = data.vitreousPotassiumMmolL;
  const vun = data.ureaNitrogenMgDl ?? 18;
  const na = data.vitreousSodiumMmolL ?? 140;

  const rawPmiMadea = Math.max(0, 5.26 * (k - 4.0));
  const rawPmiSturner = Math.max(0, 7.14 * k - 39.1);

  return (
    <div id="metabolomics-card" className="scroll-mt-20 rounded-xl bg-slate-900/90 border border-slate-800 p-5 space-y-4 transition-all">
      {/* Header with Toggle & Collapse */}
      <div className="flex items-center justify-between border-b border-slate-800/80 pb-3">
        <div className="flex items-center gap-3">
          <div className="w-9 h-9 rounded-xl bg-teal-500/10 border border-teal-500/30 flex items-center justify-center text-teal-400">
            <TestTube2 className="w-5 h-5" />
          </div>
          <div>
            <h3 className="text-base font-semibold text-slate-100 flex items-center gap-2 flex-wrap">
              <span>Metabolomics & Vitreous Electrolyte Triad</span>
              <span className="text-[11px] font-medium px-2 py-0.5 rounded-md bg-teal-950/80 text-teal-400 border border-teal-800/50">
                0 – 72 Hours
              </span>
              {data.recordedAt && (
                <span className="text-[10px] font-mono text-teal-300 px-2 py-0.5 rounded-md bg-slate-950/90 border border-slate-800 flex items-center gap-1">
                  <Clock className="w-3 h-3 text-teal-400" />
                  <span>Logged: {formatIndicatorTimestamp(data.recordedAt)}</span>
                </span>
              )}
            </h3>
            <p className="text-xs text-slate-400">
              Vitreous humor [K⁺], [Na⁺], and VUN triad kinetics with multi-analyte physiological validation
            </p>
          </div>
        </div>

        <div className="flex items-center gap-3">
          {/* Active/Bypassed Switch */}
          <label className="relative inline-flex items-center cursor-pointer">
            <input
              type="checkbox"
              checked={data.enabled}
              onChange={(e) => onChange({ ...data, enabled: e.target.checked })}
              className="sr-only peer"
            />
            <div className="w-11 h-6 bg-slate-800 peer-focus:outline-none rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-slate-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-teal-600"></div>
            <span className="ml-2 text-xs font-medium text-slate-300 hidden sm:inline">
              {data.enabled ? "Active" : "Bypassed"}
            </span>
          </label>

          {/* Module Box Collapse Button */}
          <button
            type="button"
            onClick={toggleCollapse}
            className="p-1.5 rounded-lg text-slate-400 hover:text-slate-200 hover:bg-slate-800 transition-colors cursor-pointer"
            title={isCollapsed ? "Expand module" : "Collapse module"}
          >
            {isCollapsed ? <ChevronDown className="w-4 h-4" /> : <ChevronUp className="w-4 h-4" />}
          </button>
        </div>
      </div>

      {!isCollapsed && (
        <>
          {data.enabled ? (
            <div className="space-y-4">
              {/* PRIMARY FORENSIC VITREOUS ELECTROLYTE TRIAD */}
              <div className="bg-slate-950/70 p-4 rounded-xl border border-slate-800/90 space-y-4">
                <div className="flex items-center justify-between">
                  <div>
                    <h4 className="text-xs font-bold text-teal-400 uppercase tracking-wider flex items-center gap-1.5">
                      <FlaskConical className="w-4 h-4 text-teal-400" /> Standard Forensic Vitreous Triad ([K⁺], VUN, [Na⁺])
                    </h4>
                    <p className="text-[11px] text-slate-400 mt-0.5">
                      In forensic pathology, Vitreous Potassium ([K⁺]) cannot be accurately interpreted without concurrent VUN (uremia validator) and [Na⁺] (hydration validator).
                    </p>
                  </div>
                </div>

                {/* 1. Vitreous Potassium ([K+]) */}
                <div className="bg-slate-900/80 p-3.5 rounded-xl border border-slate-800 space-y-2.5">
                  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 text-xs">
                    <span className="font-semibold text-slate-200 flex items-center gap-1.5">
                      <span className="w-2 h-2 rounded-full bg-teal-400"></span>
                      <span>Primary Marker: Vitreous Potassium ([K⁺])</span>
                      <span className="text-[10px] text-slate-400 font-normal">(Post-Mortem Autolysis Clock)</span>
                    </span>
                    <div className="flex items-center gap-2">
                      <span className="text-teal-400 font-mono font-bold text-sm">{k.toFixed(1)} mmol/L</span>
                      <select
                        value={k.toFixed(1)}
                        onChange={(e) => onChange({ ...data, vitreousPotassiumMmolL: parseFloat(e.target.value) })}
                        className="bg-slate-950 border border-slate-700 text-slate-200 text-xs rounded-lg px-2 py-1 focus:outline-none focus:border-teal-500 cursor-pointer"
                      >
                        <option value="4.0">4.0 mmol/L (Baseline / ~0h)</option>
                        <option value="5.5">5.5 mmol/L (Early / ~8h)</option>
                        <option value="7.0">7.0 mmol/L (~16h)</option>
                        <option value="8.5">8.5 mmol/L (~24h)</option>
                        <option value="11.0">11.0 mmol/L (~37h)</option>
                        <option value="14.0">14.0 mmol/L (~52h)</option>
                        <option value="17.0">17.0 mmol/L (~68h)</option>
                      </select>
                    </div>
                  </div>

                  <input
                    type="range"
                    min="3.5"
                    max="20.0"
                    step="0.1"
                    value={k}
                    onChange={(e) => onChange({ ...data, vitreousPotassiumMmolL: parseFloat(e.target.value) })}
                    className="w-full h-1.5 bg-slate-800 rounded-lg appearance-none cursor-pointer accent-teal-400"
                  />
                  <div className="flex justify-between text-[10px] text-slate-500 font-mono">
                    <span>3.5 mmol/L (Physiological)</span>
                    <span>8.0 mmol/L (~21h)</span>
                    <span>14.0 mmol/L (~52h)</span>
                    <span>20.0 mmol/L (Extreme autolysis)</span>
                  </div>
                </div>

                {/* 2. Vitreous Urea Nitrogen (VUN) */}
                <div className="bg-slate-900/80 p-3.5 rounded-xl border border-slate-800 space-y-2.5">
                  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 text-xs">
                    <span className="font-semibold text-slate-200 flex items-center gap-1.5">
                      <span className="w-2 h-2 rounded-full bg-amber-400"></span>
                      <span>Renal Validator: Vitreous Urea Nitrogen (VUN)</span>
                      <span className="text-[10px] text-slate-400 font-normal">(Antemortem Azotemia / Uremia Guard)</span>
                    </span>
                    <div className="flex items-center gap-2">
                      <div className="flex items-center gap-1 bg-slate-950 px-2 py-1 rounded border border-slate-700">
                        <input
                          type="number"
                          min="8"
                          max="120"
                          step="1"
                          value={vun}
                          onChange={(e) => onChange({ ...data, ureaNitrogenMgDl: parseFloat(e.target.value) || 0 })}
                          className="w-12 bg-transparent text-amber-300 font-mono font-bold text-xs focus:outline-none text-right"
                        />
                        <span className="text-slate-400 font-mono text-xs">mg/dL</span>
                      </div>
                      <span
                        className={`text-[10px] font-semibold px-2 py-0.5 rounded ${
                          vun > 35
                            ? "bg-rose-950/80 text-rose-300 border border-rose-800"
                            : vun > 28
                            ? "bg-amber-950/80 text-amber-300 border border-amber-800"
                            : "bg-emerald-950/80 text-emerald-300 border border-emerald-800"
                        }`}
                      >
                        {vun > 35
                          ? `Uremic Offset Active (-${result.kExcessSubtracted.toFixed(2)} mmol/L [K⁺])`
                          : vun > 28
                          ? "Mild Azotemia (29–35 mg/dL)"
                          : "Normal (10–25 mg/dL) — Baseline Intact"}
                      </span>
                    </div>
                  </div>

                  <input
                    type="range"
                    min="8"
                    max="120"
                    step="1"
                    value={vun}
                    onChange={(e) => onChange({ ...data, ureaNitrogenMgDl: parseFloat(e.target.value) })}
                    className="w-full h-1.5 bg-slate-800 rounded-lg appearance-none cursor-pointer accent-amber-400"
                  />
                  <div className="flex flex-wrap items-center justify-between gap-1 text-[10px] text-slate-400">
                    <span className="text-slate-500">Preset Scenarios:</span>
                    <div className="flex items-center gap-1.5 flex-wrap">
                      <button
                        type="button"
                        onClick={() => onChange({ ...data, ureaNitrogenMgDl: 18 })}
                        className={`px-2 py-0.5 rounded text-[10px] font-mono cursor-pointer transition-colors ${
                          vun === 18 ? "bg-teal-700 text-white" : "bg-slate-950 hover:bg-slate-800 text-slate-300 border border-slate-800"
                        }`}
                      >
                        18 mg/dL (Normal)
                      </button>
                      <button
                        type="button"
                        onClick={() => onChange({ ...data, ureaNitrogenMgDl: 32 })}
                        className={`px-2 py-0.5 rounded text-[10px] font-mono cursor-pointer transition-colors ${
                          vun === 32 ? "bg-amber-700 text-white" : "bg-slate-950 hover:bg-slate-800 text-slate-300 border border-slate-800"
                        }`}
                      >
                        32 mg/dL (Mild Azotemia)
                      </button>
                      <button
                        type="button"
                        onClick={() => onChange({ ...data, ureaNitrogenMgDl: 65 })}
                        className={`px-2 py-0.5 rounded text-[10px] font-mono cursor-pointer transition-colors ${
                          vun === 65 ? "bg-rose-700 text-white" : "bg-slate-950 hover:bg-slate-800 text-slate-300 border border-slate-800"
                        }`}
                      >
                        65 mg/dL (Uremic State)
                      </button>
                      <button
                        type="button"
                        onClick={() => onChange({ ...data, ureaNitrogenMgDl: 95 })}
                        className={`px-2 py-0.5 rounded text-[10px] font-mono cursor-pointer transition-colors ${
                          vun === 95 ? "bg-rose-700 text-white" : "bg-slate-950 hover:bg-slate-800 text-slate-300 border border-slate-800"
                        }`}
                      >
                        95 mg/dL (Severe Renal Failure)
                      </button>
                    </div>
                  </div>
                  <p className="text-[11px] text-slate-400">
                    Vitreous urea nitrogen is stable post-mortem. Elevation &gt;30–35 mg/dL confirms antemortem azotemia, proving the decedent died with elevated baseline potassium (hyperkalemia) rather than post-mortem autolysis.
                  </p>
                </div>

                {/* 3. Vitreous Sodium ([Na+]) */}
                <div className="bg-slate-900/80 p-3.5 rounded-xl border border-slate-800 space-y-2.5">
                  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 text-xs">
                    <span className="font-semibold text-slate-200 flex items-center gap-1.5">
                      <span className="w-2 h-2 rounded-full bg-cyan-400"></span>
                      <span>Hydration & Rate Validator: Vitreous Sodium ([Na⁺])</span>
                      <span className="text-[10px] text-slate-400 font-normal">(Dehydration Guard & Linear Decline)</span>
                    </span>
                    <div className="flex items-center gap-2">
                      <div className="flex items-center gap-1 bg-slate-950 px-2 py-1 rounded border border-slate-700">
                        <input
                          type="number"
                          min="100"
                          max="180"
                          step="1"
                          value={na}
                          onChange={(e) => onChange({ ...data, vitreousSodiumMmolL: parseFloat(e.target.value) || 0 })}
                          className="w-12 bg-transparent text-cyan-300 font-mono font-bold text-xs focus:outline-none text-right"
                        />
                        <span className="text-slate-400 font-mono text-xs">mmol/L</span>
                      </div>
                      <span
                        className={`text-[10px] font-semibold px-2 py-0.5 rounded ${
                          na > 152
                            ? "bg-amber-950/80 text-amber-300 border border-amber-800"
                            : na < 125
                            ? "bg-amber-950/80 text-amber-300 border border-amber-800"
                            : "bg-emerald-950/80 text-emerald-300 border border-emerald-800"
                        }`}
                      >
                        {na > 152
                          ? `Hypernatremic Dehydration (÷${result.dehydrationRatio.toFixed(2)} [K⁺] factor)`
                          : na < 125
                          ? "Hyponatremic Dilution / Submersion"
                          : `Normal Equilibrium (${result.naPmiEstimate ? `Coe Est: ~${result.naPmiEstimate}h` : "135–150 mmol/L"})`}
                      </span>
                    </div>
                  </div>

                  <input
                    type="range"
                    min="100"
                    max="180"
                    step="1"
                    value={na}
                    onChange={(e) => onChange({ ...data, vitreousSodiumMmolL: parseFloat(e.target.value) })}
                    className="w-full h-1.5 bg-slate-800 rounded-lg appearance-none cursor-pointer accent-cyan-400"
                  />
                  <div className="flex flex-wrap items-center justify-between gap-1 text-[10px] text-slate-400">
                    <span className="text-slate-500">Preset Scenarios:</span>
                    <div className="flex items-center gap-1.5 flex-wrap">
                      <button
                        type="button"
                        onClick={() => onChange({ ...data, vitreousSodiumMmolL: 140 })}
                        className={`px-2 py-0.5 rounded text-[10px] font-mono cursor-pointer transition-colors ${
                          na === 140 ? "bg-teal-700 text-white" : "bg-slate-950 hover:bg-slate-800 text-slate-300 border border-slate-800"
                        }`}
                      >
                        140 mmol/L (Equilibrium)
                      </button>
                      <button
                        type="button"
                        onClick={() => onChange({ ...data, vitreousSodiumMmolL: 128 })}
                        className={`px-2 py-0.5 rounded text-[10px] font-mono cursor-pointer transition-colors ${
                          na === 128 ? "bg-cyan-700 text-white" : "bg-slate-950 hover:bg-slate-800 text-slate-300 border border-slate-800"
                        }`}
                      >
                        128 mmol/L (Coe Decline ~28h)
                      </button>
                      <button
                        type="button"
                        onClick={() => onChange({ ...data, vitreousSodiumMmolL: 165 })}
                        className={`px-2 py-0.5 rounded text-[10px] font-mono cursor-pointer transition-colors ${
                          na === 165 ? "bg-amber-700 text-white" : "bg-slate-950 hover:bg-slate-800 text-slate-300 border border-slate-800"
                        }`}
                      >
                        165 mmol/L (Severe Dehydration)
                      </button>
                      <button
                        type="button"
                        onClick={() => onChange({ ...data, vitreousSodiumMmolL: 115 })}
                        className={`px-2 py-0.5 rounded text-[10px] font-mono cursor-pointer transition-colors ${
                          na === 115 ? "bg-rose-700 text-white" : "bg-slate-950 hover:bg-slate-800 text-slate-300 border border-slate-800"
                        }`}
                      >
                        115 mmol/L (Water Intoxication / Dilution)
                      </button>
                    </div>
                  </div>
                  <p className="text-[11px] text-slate-400">
                    Vitreous [Na⁺] normally undergoes slow post-mortem decline (~0.5 mmol/L per hour from 142 baseline). Severe dehydration (&gt;152 mmol/L) hemoconcentrates all vitreous solutes, falsely inflating potassium readings.
                  </p>
                </div>
              </div>

              {/* INTERACTIVE BIOCHEMICAL IMPACT & KINETICS PIPELINE */}
              <div className="bg-slate-950/80 p-4 rounded-xl border border-teal-900/60 space-y-3">
                <div className="flex items-center justify-between">
                  <h4 className="text-xs font-bold text-slate-200 uppercase tracking-wider flex items-center gap-1.5">
                    <Zap className="w-3.5 h-3.5 text-teal-400" />
                    <span>Dynamic Biochemical Correction & Formula Execution</span>
                  </h4>
                  {(result.kExcessSubtracted > 0 || result.dehydrationRatio > 1.0) && (
                    <span className="text-[10px] font-bold px-2 py-0.5 rounded bg-rose-950 text-rose-300 border border-rose-800">
                      Electrolyte Correction Active
                    </span>
                  )}
                </div>

                {/* Flow steps */}
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-xs">
                  <div className="bg-slate-900/90 p-2.5 rounded-lg border border-slate-800">
                    <div className="text-[10px] text-slate-400 uppercase font-semibold">1. Measured [K⁺]</div>
                    <div className="font-mono text-slate-200 font-bold text-sm mt-0.5">{k.toFixed(1)} mmol/L</div>
                    <div className="text-[10px] text-slate-500">Raw lab aspiration</div>
                  </div>

                  <div className="bg-slate-900/90 p-2.5 rounded-lg border border-slate-800">
                    <div className="text-[10px] text-slate-400 uppercase font-semibold">2. VUN Uremic Offset</div>
                    <div className={`font-mono font-bold text-sm mt-0.5 ${result.kExcessSubtracted > 0 ? "text-rose-400" : "text-slate-400"}`}>
                      {result.kExcessSubtracted > 0 ? `-${result.kExcessSubtracted.toFixed(2)} mmol/L` : "0.00 mmol/L"}
                    </div>
                    <div className="text-[10px] text-slate-500">
                      {result.kExcessSubtracted > 0 ? "Azotemic excess deducted" : "Baseline K intact"}
                    </div>
                  </div>

                  <div className="bg-slate-900/90 p-2.5 rounded-lg border border-slate-800">
                    <div className="text-[10px] text-slate-400 uppercase font-semibold">3. Hydration Factor</div>
                    <div className={`font-mono font-bold text-sm mt-0.5 ${result.dehydrationRatio > 1.0 ? "text-amber-400" : "text-slate-400"}`}>
                      {result.dehydrationRatio > 1.0 ? `÷${result.dehydrationRatio.toFixed(2)}` : "1.00×"}
                    </div>
                    <div className="text-[10px] text-slate-500">
                      {result.dehydrationRatio > 1.0 ? "Solute hemoconcentration" : "Normal fluid balance"}
                    </div>
                  </div>

                  <div className="bg-slate-900/90 p-2.5 rounded-lg border border-teal-800/80 bg-teal-950/20">
                    <div className="text-[10px] text-teal-400 uppercase font-semibold">4. Effective [K⁺] Applied</div>
                    <div className="font-mono text-teal-300 font-bold text-sm mt-0.5">
                      {result.effectivePotassiumMmolL.toFixed(2)} mmol/L
                    </div>
                    <div className="text-[10px] text-teal-400/70">Fed to Madea & Sturner</div>
                  </div>
                </div>

                {/* Formula comparison grid with corrected vs uncorrected */}
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-xs pt-1">
                  <div className="bg-slate-900/70 p-3 rounded-lg border border-slate-800">
                    <div className="flex items-center justify-between">
                      <div className="font-semibold text-slate-200">Madea Linear Formula</div>
                      <span className="font-mono text-teal-300 font-bold text-sm">{result.pmiMadea.toFixed(1)} h</span>
                    </div>
                    <div className="text-[11px] text-slate-400 mt-1">PMI = 5.26 × ([K⁺] - 4.0)</div>
                    {(result.kExcessSubtracted > 0 || result.dehydrationRatio > 1.0) && (
                      <div className="text-[10px] text-amber-400/90 mt-1.5 pt-1.5 border-t border-slate-800">
                        Raw uncorrected: <span className="font-mono">{rawPmiMadea.toFixed(1)}h</span>
                        <span className="text-emerald-400 ml-1">
                          ({Math.abs(rawPmiMadea - result.pmiMadea).toFixed(1)}h false overestimation avoided)
                        </span>
                      </div>
                    )}
                  </div>

                  <div className="bg-slate-900/70 p-3 rounded-lg border border-slate-800">
                    <div className="flex items-center justify-between">
                      <div className="font-semibold text-slate-200">Sturner Regression</div>
                      <span className="font-mono text-teal-300 font-bold text-sm">{result.pmiSturner.toFixed(1)} h</span>
                    </div>
                    <div className="text-[11px] text-slate-400 mt-1">PMI = 7.14 × [K⁺] - 39.1</div>
                    {(result.kExcessSubtracted > 0 || result.dehydrationRatio > 1.0) && (
                      <div className="text-[10px] text-amber-400/90 mt-1.5 pt-1.5 border-t border-slate-800">
                        Raw uncorrected: <span className="font-mono">{rawPmiSturner.toFixed(1)}h</span>
                        <span className="text-emerald-400 ml-1">
                          ({Math.abs(rawPmiSturner - result.pmiSturner).toFixed(1)}h false overestimation avoided)
                        </span>
                      </div>
                    )}
                  </div>

                  <div className="bg-slate-900/70 p-3 rounded-lg border border-slate-800">
                    <div className="flex items-center justify-between">
                      <div className="font-semibold text-slate-200">Coe [Na⁺] Decline Model</div>
                      <span className="font-mono text-cyan-300 font-bold text-sm">
                        {result.naPmiEstimate !== undefined ? `${result.naPmiEstimate.toFixed(1)} h` : "Equilibrium"}
                      </span>
                    </div>
                    <div className="text-[11px] text-slate-400 mt-1">PMI ≈ (142 - [Na⁺]) / 0.5</div>
                    <div className="text-[10px] text-slate-500 mt-1.5 pt-1.5 border-t border-slate-800">
                      {result.naPmiEstimate !== undefined
                        ? "Independent chronometer corroborating [K⁺]"
                        : "[Na⁺] within antemortem equilibrium"}
                    </div>
                  </div>
                </div>

                {/* Contextual Alert Banner if correction active */}
                {result.kExcessSubtracted > 0 && (
                  <div className="bg-rose-950/40 border border-rose-900/60 p-3 rounded-lg text-xs text-rose-200 flex items-start gap-2">
                    <ShieldAlert className="w-4 h-4 text-rose-400 shrink-0 mt-0.5" />
                    <div>
                      <span className="font-bold">Antemortem Uremia Correction Active (VUN = {vun} mg/dL):</span>{" "}
                      Because antemortem baseline potassium was elevated by ~{result.kExcessSubtracted.toFixed(2)} mmol/L due to impaired renal excretion, using raw [K⁺] ({k.toFixed(1)} mmol/L) would have erroneously placed time of death {Math.abs(rawPmiMadea - result.pmiMadea).toFixed(1)} hours earlier than actual. Corrected effective [K⁺] ({result.effectivePotassiumMmolL.toFixed(2)} mmol/L) preserves forensic accuracy.
                    </div>
                  </div>
                )}

                {result.dehydrationRatio > 1.0 && (
                  <div className="bg-amber-950/40 border border-amber-900/60 p-3 rounded-lg text-xs text-amber-200 flex items-start gap-2">
                    <Droplets className="w-4 h-4 text-amber-400 shrink-0 mt-0.5" />
                    <div>
                      <span className="font-bold">Hypernatremic Dehydration Correction Active ([Na⁺] = {na} mmol/L):</span>{" "}
                      Severe fluid depletion hemoconcentrated vitreous humor solutes by a factor of {result.dehydrationRatio.toFixed(2)}×. The normalization algorithm counteracts artificial potassium elevation.
                    </div>
                  </div>
                )}
              </div>

              {/* Add Secondary Research Metabolites */}
              <div className="bg-slate-950/60 p-4 rounded-xl border border-teal-900/40 space-y-3">
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
                  <div>
                    <h4 className="text-xs font-bold text-slate-200 uppercase tracking-wider flex items-center gap-1.5">
                      <Sparkles className="w-3.5 h-3.5 text-teal-400" /> Additional Biochemical Analytes (Research Panel)
                    </h4>
                    <p className="text-[11px] text-slate-400">
                      Add supplementary markers (Hypoxanthine, Lactate, Glucose, Inosine, CSF) to expand multi-analyte consensus
                    </p>
                  </div>

                  <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-2 w-full sm:w-auto">
                    <select
                      value={selectedCatalogKey}
                      onChange={(e) => setSelectedCatalogKey(e.target.value)}
                      className="bg-slate-900 border border-teal-700/60 text-slate-200 text-xs rounded-xl px-3 py-2 focus:outline-none focus:border-teal-400 cursor-pointer w-full sm:w-auto sm:min-w-[200px]"
                    >
                      {METABOLITE_CATALOG.filter(
                        (m) =>
                          m.key !== "vitreous_potassium" &&
                          m.key !== "urea_nitrogen" &&
                          m.key !== "vitreous_sodium"
                      ).map((cat) => (
                        <option key={cat.key} value={cat.key}>
                          {cat.name} ({cat.unit})
                        </option>
                      ))}
                    </select>

                    <button
                      type="button"
                      onClick={handleAddMetabolite}
                      className="px-3.5 py-2 rounded-xl bg-teal-600 hover:bg-teal-500 text-white text-xs font-semibold flex items-center justify-center gap-1.5 transition-colors cursor-pointer shadow-sm shrink-0"
                    >
                      <Plus className="w-3.5 h-3.5" />
                      <span>Add Analyte</span>
                    </button>
                  </div>
                </div>

                {/* List of Active User-Selected Metabolites */}
                {activeMetabolites.length > 0 ? (
                  <div className="space-y-2.5 pt-2">
                    {activeMetabolites.map((item) => {
                      const catalogDef = METABOLITE_CATALOG.find((c) => c.key === item.metaboliteKey);
                      const min = catalogDef?.min || 0;
                      const max = catalogDef?.max || 100;
                      const step = catalogDef?.step || 1;

                      return (
                        <div
                          key={item.id}
                          className="bg-slate-900/90 border border-slate-800 p-3.5 rounded-xl flex flex-col sm:flex-row sm:items-center justify-between gap-3 text-xs"
                        >
                          <div className="space-y-1 min-w-0 flex-1">
                            <div className="flex items-center gap-2">
                              <span className="font-bold text-slate-200">{item.name}</span>
                              <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-teal-950 text-teal-300 border border-teal-800/60">
                                Ref: {item.referenceRange}
                              </span>
                            </div>
                            <p className="text-[11px] text-slate-400">{item.notes}</p>
                          </div>

                          <div className="flex items-center gap-3 shrink-0">
                            {/* Measured value input */}
                            <div className="flex items-center gap-1.5 bg-slate-950 px-2.5 py-1.5 rounded-lg border border-slate-700">
                              <span className="text-[10px] text-slate-400 uppercase font-semibold">Value:</span>
                              <input
                                type="number"
                                min={min}
                                max={max}
                                step={step}
                                value={item.measuredValue}
                                onChange={(e) => {
                                  const val = parseFloat(e.target.value) || 0;
                                  handleUpdateMetaboliteValue(item.id, val);
                                }}
                                className="w-16 bg-transparent text-teal-300 font-mono font-bold text-xs focus:outline-none text-right"
                              />
                              <span className="text-slate-400 font-mono text-xs">{item.unit}</span>
                            </div>

                            {/* Estimated Individual Contribution */}
                            {item.pmiContributionHours > 0 && (
                              <div className="text-right">
                                <div className="text-[10px] text-slate-400">Est. PMI</div>
                                <div className="font-mono text-teal-400 font-bold text-xs">
                                  ~{item.pmiContributionHours}h
                                </div>
                              </div>
                            )}

                            {/* Delete Button */}
                            <button
                              type="button"
                              onClick={() => handleRemoveMetabolite(item.id)}
                              className="p-2 rounded-lg text-slate-400 hover:text-rose-400 hover:bg-rose-950/40 transition-colors cursor-pointer"
                              title="Remove metabolite"
                            >
                              <Trash2 className="w-4 h-4" />
                            </button>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                ) : (
                  <div className="text-center py-3 text-slate-500 text-xs border border-dashed border-slate-800 rounded-xl">
                    No secondary research analytes added. Use the dropdown above (e.g. Hypoxanthine, Lactate, Glucose) to include additional biochemical chronometers.
                  </div>
                )}
              </div>

              {/* Renal Failure / Ocular Hemorrhage Guard */}
              <div className="bg-slate-950/40 p-4 rounded-xl border border-slate-800/60 text-xs">
                <label className="flex items-center gap-2 cursor-pointer text-slate-300">
                  <input
                    type="checkbox"
                    checked={data.suspectedRenalFailureOrTrauma}
                    onChange={(e) => onChange({ ...data, suspectedRenalFailureOrTrauma: e.target.checked })}
                    className="rounded bg-slate-800 border-slate-700 text-teal-500 focus:ring-0 cursor-pointer"
                  />
                  <AlertCircle className="w-3.5 h-3.5 text-amber-400 shrink-0" />
                  <span>Suspected Pre-Mortem Uremia / Renal Failure / Direct Ocular Trauma</span>
                </label>
                {data.suspectedRenalFailureOrTrauma && (
                  <p className="text-xs text-amber-300/90 mt-2 pl-5 leading-relaxed">
                    Clinical Caveat: Pre-mortem hyperkalemia or ocular blood contamination can falsely elevate vitreous potassium levels, skewing interval estimations upward.
                  </p>
                )}
              </div>

              {/* Quick Outcome Bar */}
              <div className="bg-gradient-to-r from-slate-950 via-slate-900 to-teal-950/40 p-3.5 rounded-xl border border-teal-900/40 flex flex-wrap items-center justify-between gap-2 text-xs">
                <div className="flex items-center gap-2">
                  <CheckCircle2 className="w-4 h-4 text-teal-400" />
                  <div>
                    <span className="text-slate-400">Metabolomics Consensus:</span>{" "}
                    <span className="text-teal-300 font-bold font-mono">
                      {result.optimalHours}h
                    </span>{" "}
                    <span className="text-slate-400 text-xs">
                      (Estimated window: {result.minHours} – {result.maxHours} h)
                    </span>
                  </div>
                </div>
                <span className="text-emerald-400 font-semibold text-xs">{result.confidence}% Confidence</span>
              </div>

              {/* Collapsible Extra Scientific Guidance */}
              <div className="border border-slate-800/70 rounded-xl overflow-hidden bg-slate-950/30 text-xs">
                <button
                  type="button"
                  onClick={() => setShowExtraInfo(!showExtraInfo)}
                  className="w-full p-3 flex items-center justify-between text-slate-400 hover:text-slate-200 hover:bg-slate-900/50 transition-colors cursor-pointer text-left"
                >
                  <span className="flex items-center gap-2 font-medium">
                    <HelpCircle className="w-3.5 h-3.5 text-teal-400" />
                    <span>Scientific Context & Vitreous Electrolyte Sampling Protocol</span>
                  </span>
                  {showExtraInfo ? (
                    <ChevronUp className="w-3.5 h-3.5 text-slate-500" />
                  ) : (
                    <ChevronDown className="w-3.5 h-3.5 text-slate-500" />
                  )}
                </button>
                {showExtraInfo && (
                  <div className="p-4 border-t border-slate-800/60 space-y-2 text-slate-400 leading-relaxed bg-slate-950/50">
                    <p>
                      <strong>Vitreous Humor Physiology:</strong> Following circulatory arrest, selective retinal cell permeability breaks down, causing linear diffusion of potassium ions from intracellular to extracellular vitreous humor.
                    </p>
                    <ul className="list-disc pl-5 space-y-1 text-slate-400">
                      <li><strong>Sampling Protocol:</strong> Extract clear, non-hemolyzed vitreous humor from the lateral canthus using a 20-gauge needle.</li>
                      <li><strong>Protected Reservoir:</strong> The eye remains anatomically isolated, making vitreous potassium less susceptible to immediate environmental changes than peripheral blood.</li>
                    </ul>
                  </div>
                )}
              </div>
            </div>
          ) : (
            <div className="p-4 rounded-xl bg-slate-950/40 border border-slate-800 text-xs text-slate-500 flex items-center gap-2">
              <Info className="w-4 h-4 text-slate-600" />
              Metabolomics testing is bypassed.
            </div>
          )}
        </>
      )}
    </div>
  );
};

export default MetabolomicsInput;
